-- Migration V1: criação das tabelas base de autenticação e autorização.
-- tb_user e tb_role possuem chave primária gerada por identidade.
-- A relação ManyToMany é materializada por tb_user_role, cuja chave primária
-- composta (user_id, role_id) impede associações duplicadas entre usuário e papel.
-- As foreign keys utilizam ON DELETE CASCADE para manter integridade referencial:
-- por exemplo, se o usuário de id = 5 for removido de tb_user, todas as linhas
-- em tb_user_role com user_id = 5 serão automaticamente excluídas,
-- evitando registros órfãos na tabela de junção.

CREATE TABLE tb_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE tb_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE tb_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user_role_user
      FOREIGN KEY (user_id)
          REFERENCES tb_user (id)
          ON DELETE CASCADE,

    CONSTRAINT fk_user_role_role
      FOREIGN KEY (role_id)
          REFERENCES tb_role (id)
          ON DELETE CASCADE
);