CREATE TABLE tb_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    price NUMERIC(10,2) NOT NULL,
    stock_quantity INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE tb_product_category (
    product_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    CONSTRAINT pk_product_category
    PRIMARY KEY (product_id, category_id),

    CONSTRAINT fk_product_category_product
    FOREIGN KEY (product_id)
    REFERENCES tb_product(id)
    ON DELETE CASCADE,

    CONSTRAINT fk_product_category_category
    FOREIGN KEY (category_id)
    REFERENCES tb_category(id)
    ON DELETE CASCADE
);